### ISSUE TITLE
Assertion `targetNumberOfColors % 2 == 0' failed

### ISSUE THREAD

**Issue by njutcz** [ARM-software/HPCG_for_Arm#1]
When I run the programm built with HPCG_USE_NEON on Kunpeng 920, an error has occurred. In OptimizeProblem.cpp, assertion 'targetNumberOfColors % 2 == 0' failed. Do you have the similar problem and how can I solve the problem？

**Comment by danruimu** [comment]
Hello,

Can you please share the values chosen for `nx`, `ny` and `nz` for the runs you are performing? It looks like at some of the levels `nz` is not an even number.

As stated in the `README`, for every level of the grid, `nx`, `ny` and `nz` must be and odd number and must be greater or equal to 32 for the finest level of the grid. This means that, the smallest size that can be run `nx=32`, `ny=32` and `nz=32`.

Regarding the even number constraint. HPCG uses generates 4 grid levels. The dimensions of each level can be computed as:

```
nx_i = nx / 2^i
ny_i = ny / 2^i
nz_i = nz / 2^i
```

Being `n{x,y,z}_i` the size of the dimension `{x,y,z}` for the `i-th` level. So, a size of `nx=ny=nz=32` would be valid since the values 32, 16, 8 and 4 are even numbers. A size of `nx=ny=nz=40` won't be valid since sizes for each level would 40, 20, 10 and 5, and 5 is not an even number.

**Comment by njutcz** [comment]
OK， I know. I  run with the default values. (nx=ny=nz=104).
I think I should learn your algorithm.   Thanks for your answer!

**Comment by danruimu** [comment]
For further information about the code, I suggest looking into the documentation linked at the `README.md` file.

Closing this ticket now. Please reopened if you face the same issue again with the solution provided or if you encounter any other issues.
